name: development
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage --enable-test-discovery --sanitize=thread
  ubuntu_bionic:
    container: 
      image: swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage --enable-test-discovery --sanitize=thread
  ubuntu_xenial:
    container: 
      image: swift:5.1-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage --enable-test-discovery --sanitize=thread
